# Generated by Django 5.1.6 on 2025-02-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0002_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='User',
            new_name='user',
        ),
    ]
